lunches/lunches/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from .settings import MEDIA_ROOT, MEDIA_URL


from buy_lunch.views import ShowMenu, AddLunch, AddAppetizer, AddBeverage, ShowLunches, ShowLAppetizers, ShowBeverages,\
    MakeOrder, UserOrders, LunchCalendar, SetMenu, EditMenu, ReviewOrder, RegisterView, AllOrders, DishRanking, \
    MenuDetails, TodayOrders, Users, UserDetails, LunchReview, OrderConfirm

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='logout.html'), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),

    path('', ShowMenu.as_view(), name='index'),
    path('add-lunch/', AddLunch.as_view(), name='add-lunch'),
    path('add-appetizer/', AddAppetizer.as_view(), name='add-appetizer'),
    path('add-beverage/', AddBeverage.as_view(), name='add-beverage'),
    path('lunches/', ShowLunches.as_view(), name='lunches'),
    path('appetizers/', ShowLAppetizers.as_view(), name='appetizers'),
    path('beverages/', ShowBeverages.as_view(), name='beverages'),
    path('make-order/', MakeOrder.as_view(), name='make-order'),
    path('user-orders/', UserOrders.as_view(), name='user-orders'),
    path('lunch-calendar/', LunchCalendar.as_view(), name='lunch-calendar'),
    path('set-menu/', SetMenu.as_view(), name='set-menu'),
    path('order-review/<int:order_id>', ReviewOrder.as_view(), name='order-review'),
    path('edit-menu/<int:menu_id>', EditMenu.as_view(), name='edit-menu'),
    path('menu-details/<int:menu_id>', MenuDetails.as_view(), name='menu-details'),
    path('all-orders/', AllOrders.as_view(), name='all-orders'),
    path('ranking/', DishRanking.as_view(), name='ranking'),
    path('today-orders/', TodayOrders.as_view(), name='today-orders'),
    path('users/', Users.as_view(), name='users'),
    path('user-details/<int:user_id>', UserDetails.as_view(), name='user-details'),
    path('review/<int:review_id>', LunchReview.as_view(), name='review'),
    path('confirm-order/<int:order_id>', OrderConfirm.as_view(), name='confirm-order'),



    ] + static(MEDIA_URL, document_root=MEDIA_ROOT)

lunches/buy_lunch/models.py
from django.db import models
from datetime import datetime
from django.utils import timezone
from django.contrib.auth.models import User


LUNCH_TYPE = ((1, 'mięsny'),
              (2, 'wegetariański'),
              (3, 'wegański'))

APPETIZER_TYPE = ((1, 'sałatka'),
                  (2, 'zupa'))

STARS = ((1, '*'),
         (2, '**'),
         (3, '***'),
         (4, '****'),
         (5, '*****'))


class Lunch(models.Model):
    lunch_name = models.CharField(max_length=300, verbose_name='Nazwa')
    lunch_type = models.IntegerField(choices=LUNCH_TYPE, verbose_name='Typ')
    lunch_price = models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Cena')

    def __str__(self):
        return self.lunch_name


class Appetizer(models.Model):
    appetizer_name = models.CharField(max_length=300, verbose_name='Nazwa')
    appetizer_type = models.IntegerField(choices=APPETIZER_TYPE, verbose_name='Typ')
    appetizer_price = models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Cena')

    def __str__(self):
        return self.appetizer_name


class Beverages(models.Model):
    beverage_name = models.CharField(max_length=100, verbose_name='Nazwa')
    beverage_price = models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Cena')

    def __str__(self):
        return self.beverage_name


class Order(models.Model):
    lunch = models.ForeignKey(Lunch, on_delete=models.CASCADE)
    appetizer = models.ForeignKey(Appetizer, on_delete=models.CASCADE, null=True)
    beverage = models.ForeignKey(Beverages, on_delete=models.CASCADE, null=True)
    final_price = models.DecimalField(decimal_places=2, max_digits=4)
    points = models.ForeignKey('Points', null=True, on_delete=models.CASCADE)
    date = models.DateTimeField(default=datetime.today)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    discount = models.IntegerField(default=0)
    points_collected = models.IntegerField(default=0)
    ready = models.BooleanField(default=False)

    def __str__(self):
        return 'Zamówienie: {}, {}, {}'.format(self.lunch, self.appetizer, self.beverage)


class Points(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    amount = models.IntegerField(default=0)


class Menu(models.Model):
    date = models.DateTimeField(default=datetime.today, unique=True, error_messages={'unique':"Lunch na ten dzień już istnieje"})
    lunch_meat = models.ForeignKey(Lunch, related_name='lunch_meat', on_delete=models.CASCADE)
    lunch_vegetarian = models.ForeignKey(Lunch, related_name='lunch_vegetarian', on_delete=models.CASCADE)
    lunch_vegan = models.ForeignKey(Lunch, related_name='lunch_vegan', on_delete=models.CASCADE)
    soup = models.ForeignKey(Appetizer, related_name='soup', on_delete=models.CASCADE)
    salad = models.ForeignKey(Appetizer, related_name='salad', on_delete=models.CASCADE)


class MenuReview(models.Model):
    review = models.TextField(verbose_name='Recenzja')
    menu = models.ForeignKey(Order, on_delete=models.CASCADE)
    lunch_stars = models.IntegerField(choices=STARS, verbose_name='Ocena lunchu')
    appetizer_stars = models.IntegerField(choices=STARS, verbose_name='Ocena przystawki')
    user = models.ForeignKey(User, on_delete=models.CASCADE)

lunches/buy_lunch/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Lunch, Appetizer, Beverages, Order, Menu, MenuReview


class AddLunchForm(forms.ModelForm):
    class Meta:
        model = Lunch
        fields = '__all__'
        widgets = {'date': forms.DateInput(attrs={'type': 'date'})}


class AddAppetizerForm(forms.ModelForm):
    class Meta:
        model = Appetizer
        exclude = ['date']


class AddBeverageForm(forms.ModelForm):
    class Meta:
        model = Beverages
        fields = '__all__'


class MenuForm(forms.ModelForm):
    date = forms.DateField(label='Data', widget=forms.DateInput(attrs={'type': 'date'}))
    lunch_meat = forms.ModelChoiceField(label='Lunch mięsny', queryset=Lunch.objects.filter(lunch_type='1'))
    lunch_vegetarian = forms.ModelChoiceField(label='Lunch wegetariański', queryset=Lunch.objects.filter(lunch_type='2'))
    lunch_vegan = forms.ModelChoiceField(label='Lunch wegański', queryset=Lunch.objects.filter(lunch_type='3'))
    salad = forms.ModelChoiceField(label='Sałatka', queryset=Appetizer.objects.filter(appetizer_type='1'))
    soup = forms.ModelChoiceField(label='Zupa', queryset=Appetizer.objects.filter(appetizer_type='2'))

    class Meta:
        model = Menu
        fields = ['date', 'lunch_meat', 'lunch_vegetarian', 'lunch_vegan', 'salad', 'soup']


class ReviewMenuForm(forms.ModelForm):
    class Meta:
        model = MenuReview
        fields = ['review', 'lunch_stars', 'appetizer_stars']


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

lunches/buy_lunch/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin
from django.contrib.auth.models import User

from django.http import HttpResponse, HttpResponseRedirect

from datetime import date
from django.db.models import Sum, Avg

from .models import Lunch, Appetizer, Beverages, Order, Points, Menu, MenuReview
from .forms import AddLunchForm, AddAppetizerForm, AddBeverageForm, MenuForm, ReviewMenuForm,UserRegisterForm


class PermissionView(PermissionRequiredMixin, View):
    permission_required = 'auth.add_user'


class ShowMenu(View):
    def get(self, request):
        today = date.today()
        try:
            menu = Menu.objects.get(date=today)
        except Menu.DoesNotExist:
            menu = None
        return render(request, 'index.html', {'menu': menu,
                                              'today': today})


class AddLunch(PermissionView):
    def get(self, request):
        form = AddLunchForm()
        return render(request, 'add_lunch.html', {'form': form})

    def post(self, request):
        form = AddLunchForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('lunches')


class AddAppetizer(PermissionView):
    def get(self, request):
        form = AddAppetizerForm()
        return render(request, 'add_appetizer.html', {'form': form})

    def post(self, request):
        form = AddAppetizerForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('appetizers')


class AddBeverage(PermissionView):
    def get(self, request):
        form = AddBeverageForm()
        return render(request, 'add_beverage.html', {'form': form})

    def post(self, request):
        form = AddBeverageForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('beverages')


class ShowLunches(PermissionView):
    def get(self, request):
        lunches = Lunch.objects.all().order_by('lunch_type')
        return render(request, 'show_lunches.html', {'lunches': lunches})


class ShowLAppetizers(PermissionView):
    def get(self, request):
        appetizers = Appetizer.objects.all()
        return render(request, 'show_appetizers.html', {'appetizers': appetizers})


class ShowBeverages(PermissionView):
    def get(self, request):
        beverages = Beverages.objects.all()
        return render(request, 'show_beverages.html', {'beverages': beverages})


class MakeOrder(LoginRequiredMixin, View):
    def get(self, request):
        today = date.today()
        lunch_meat = Lunch.objects.get(lunch_type=1, lunch_meat__date=today)
        lunch_vegetarian = Lunch.objects.get(lunch_type=2, lunch_vegetarian__date=today)
        lunch_vegan = Lunch.objects.get(lunch_type=3, lunch_vegan__date=today)

        salad = Appetizer.objects.get(appetizer_type=1, salad__date=today)
        soup = Appetizer.objects.get(appetizer_type=2, soup__date=today)

        beverages = Beverages.objects.all()

        count_points = Points.objects.filter(user=request.user).aggregate(Sum('amount'))
        my_points = count_points['amount__sum']

        discount = None
        discounted = 0
        points = 0

        if my_points is None:
            my_points = 0

        if my_points >= 25:
            points = my_points
            discount = '25%'
            discounted = 0.75
        elif points >= 50:
            discount = '50%'
            discounted = 0.5
        elif points >= 100:
            discount = '100%'
            discounted = 0

        return render(request, 'make_order.html', {'lunch_meat': lunch_meat,
                                                   'lunch_vegetarian': lunch_vegetarian,
                                                   'lunch_vegan': lunch_vegan,
                                                   'salad': salad,
                                                   'soup': soup,
                                                   'beverages': beverages,
                                                   'my_points': points,
                                                   'discount': discount,
                                                   'discounted': discounted})

    def post(self, request):
        try:
            lunch_selected = request.POST.get('lunch')
            lunch = Lunch.objects.get(id=lunch_selected)

            appetizer_selected = request.POST.get('appetizer')
            appetizer = Appetizer.objects.get(id=appetizer_selected)

            beverage_selected = request.POST.get('beverage')
            beverage = Beverages.objects.get(id=beverage_selected)
        except Lunch.DoesNotExist:
            lunch = None
            return redirect('make-order')
        except Appetizer.DoesNotExist:
            appetizer = None
            return redirect('make-order')
        except Beverages.DoesNotExist:
            beverage = None
            return redirect('make-order')

        final_price = lunch.lunch_price + appetizer.appetizer_price + beverage.beverage_price

        discounted = 0

        if request.POST.get('discount'):
            discount = request.POST.get('discount')

            if discount == '25%':
                discounted = 0.75
                final_price = float(final_price) * discounted
                points_removed = Points.objects.create(user=request.user,
                                                       amount=-25)
                points_removed.save()

            elif discount == '50%':
                discounted = 0.5
                final_price = float(final_price) * discounted
                points_removed = Points.objects.create(user=request.user,
                                                       amount=-50)
                points_removed.save()

            elif discount == '100%':
                discounted = 1
                final_price = 0
                points_removed = Points.objects.create(user=request.user,
                                                       amount=-100)
                points_removed.save()

        points_collected = int(final_price/10)

        if final_price > 10:
            user_points = Points.objects.create(user=self.request.user, amount=points_collected)
        else:
            user_points = None

        order = Order.objects.create(lunch=lunch,
                                     appetizer=appetizer,
                                     beverage=beverage,
                                     final_price=final_price,
                                     points=user_points,
                                     points_collected=points_collected,
                                     user=self.request.user,
                                     discount=discounted,
                                     )
        order.save()
        return redirect('user-orders')


class UserOrders(LoginRequiredMixin, View):
    def get(self, request):
        orders = Order.objects.filter(user=request.user).order_by('-date')

        return render(request, 'user_orders.html', {'orders': orders})


class LunchCalendar(PermissionView):
    def get(self, request):
        menu = Menu.objects.all()
        return render(request, 'calendar.html', {'menu': menu})


class SetMenu(PermissionView):
    def get(self, request):
        form = MenuForm()
        return render(request, 'set_menu.html', {'form': form})

    def post(self, request):
        form = MenuForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('index')
        else:
            return render(request, 'set_menu.html', {'form': form})


class MenuDetails(PermissionView):
    def get(self, request, menu_id):
        menu = Menu.objects.get(id=menu_id)
        return render(request, 'menu_details.html', {'menu': menu})


class EditMenu(PermissionView):
    def get(self, request, menu_id):
        today = date.today()
        try:
            menu = Menu.objects.get(id=menu_id, date__gte=today)
        except Menu.DoesNotExist:
            menu = None
        form = MenuForm(instance=menu)
        return render(request, 'edit_menu.html', {'form': form, 'menu': menu})

    def post(self, request, menu_id):
        menu = Menu.objects.get(id=menu_id)
        form = MenuForm(request.POST, instance=menu)
        if form.is_valid():
            form.save()
            return redirect('index')


class ReviewOrder(LoginRequiredMixin, View):
    def get(self, request, order_id):
        order = Order.objects.get(id=order_id)
        form = ReviewMenuForm()
        return render(request, 'lunch_review.html', {'form': form, 'order': order})

    def post(self, request, order_id):
        order = Order.objects.get(id=order_id)
        form = ReviewMenuForm(request.POST)
        if form.is_valid():
            review = MenuReview.objects.create(user=request.user,
                                               menu=order,
                                               review=form.cleaned_data.get('review'),
                                               lunch_stars=form.cleaned_data.get('lunch_stars'),
                                               appetizer_stars=form.cleaned_data.get('appetizer_stars'))
            review.save()
            return redirect('user-orders')


class RegisterView(View):
    def get(self, request):
        form = UserRegisterForm()
        return render(request, 'register.html', {'form': form})

    def post(self, request):
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            password = form.cleaned_data['password1']
            user.set_password(password)
            user.save()
            return redirect('login')


class AllOrders(PermissionView):
    def get(self, request):
        orders = Order.objects.all().order_by('-date')

lunches/buy_lunch/templates/add_appetizer.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
     <div class="text-center">
    <h5>Dodaj przystawkę</h5>
    <form action="{%  url 'add-appetizer' %}" method="post" class="form">
    {% csrf_token %}
    {{ form | crispy }}
    <input type="submit" value="Dodaj">

    </form>
      </div>

{% endblock %}

lunches/buy_lunch/templates/base.html
<!DOCTYPE html>

<html lang="en">
<head>
    {% load static %}
    {% load bootstrap4 %}
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}
    <link href="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.1.0/fullcalendar.min.css" rel="stylesheet" />
    <script src="https://momentjs.com/downloads/moment-with-locales.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.17.1/moment.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.10.0/fullcalendar.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.10.0/locale-all.js"></script>


    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
    <link href='http://fonts.googleapis.com/css?family=Cookie' rel='stylesheet' type='text/css'>

    <meta charset="UTF-8">
    <title>LunchTime</title>
</head>
<body class="ml-2 mr-2 mt-2" >

<header class="navbar navbar-expand-lg navbar-light bg-light mb-4" id="main-header">

  <a class="navbar-brand app-name" href="{% url 'index' %}">LunchTime</a>


  <div class="collapse navbar-collapse" id="navbarNavDropdown">




{% if user.is_staff %}
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'lunch-calendar' %}">Kalendarz</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'set-menu' %}">Ułóż menu</a>
      </li>
        <li class="nav-item">
        <a class="nav-link" href="{% url 'all-orders' %}">Historia zamówień</a>
      </li>
        <li class="nav-item">
        <a class="nav-link" href="{% url 'ranking' %}">Ranking</a>
      </li>
        <li class="nav-item">
        <a class="nav-link" href="{% url 'users' %}">Użytkownicy</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dodaj danie
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="{% url 'add-lunch' %}">Dodaj lunch</a>
            <a class="dropdown-item" href="{% url 'add-appetizer' %}">Dodaj przystawkę</a>
            <a class="dropdown-item" href="{% url 'add-beverage' %}">Dodaj napój</a>
        </div>
      </li>
    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Wszystkie dania
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="{% url 'lunches' %}">Pokaż lunche</a>
            <a class="dropdown-item" href="{% url 'appetizers' %}">Pokaż przystawki</a>
            <a class="dropdown-item" href="{% url 'beverages' %}">Pokaż napoje</a>
        </div>
      </li>
    </ul>
    {% elif user.is_authenticated %}
      <ul class="navbar-nav mr-auto">
    <li class="nav-item">
        <a class="nav-link" href="{% url 'user-orders' %}">Moje zamówienia</a>
      </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'make-order' %}">Złóż zamówienie</a>
      </li>
    </ul>

        {% endif %}

    {% if user.is_authenticated %}
        <ul class="navbar-nav ml-auto">
        <span class="navbar-text mx-2">Witaj, {{ user.username }}!</span>
            {% if not user.is_staff %}
        <span class="navbar-text mx-2">Punkty: {{ points | default_if_none:0 }}</span>
                {% endif %}
          <div class="nav-item">
            <a class="nav-link" href="{% url 'logout' %}"><img class="logout" src="/media/power.png"></a>
          </div>
         </ul>

    {% else %}
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'register' %}">Zarejestruj się</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'login' %}">Zaloguj się</a>
      </li>
    {% endif %}
    </ul>
  </div>
</nav>

</header>

        {% block content %}


        {% endblock %}
</body>

</html>

lunches/buy_lunch/templates/calendar.html
{% extends "base.html" %}

{% block content %}

<script type="text/javascript">
    $(document).ready(function() {

    // page is now ready, initialize the calendar...

    $('#calendar').fullCalendar({

        weekends: true,
        locale: 'pl',
        editable: true,
        slotEventOverlap: false,
        navLinks: true,


        header: {
                left: 'prev,next today',
                center: 'title',
                right: 'month,agendaWeek,agendaDay',
          },

        events: [
            {% for dish in menu %}
            {
                title: "{{ dish.lunch_meat.lunch_name }}\n{{ dish.lunch_vegetarian.lunch_name }}\n{{ dish.lunch_vegan.lunch_name }}\n{{ dish.salad.appetizer_name }}\n{{ dish.soup.appetizer_name }}",
                 start: "{{ dish.date |date:"Y-m-d" }}",
                 end: "{{ dish.date|date:"Y-m-d" }}",
                 url: "{% url 'menu-details' dish.id %}"

            },

            {% endfor %}

        ],
    eventColor: '#F5F5F5',
    eventTextColor: '#696969'

    });

});
</script>

<div id='calendar'></div>

{% endblock %}

lunches/buy_lunch/templates/confirm_order.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
    <div class="text-center">
    <h5>Zamówienie nr: {{ order.id }}</h5>
    <form action="{%  url 'confirm-order' order.id %}" method="post" class="form">
    {% csrf_token %}
        <div class="form-group">
            Użytkownik: {{ order.user }}
        </div>
        <div class="form-group">
            Danie główne: {{ order.lunch }}
        </div>
        <div class="form-group">
             Przystawka: {{ order.appetizer }}
        </div>
        <div class="form-group">
             Napój: {{ order.beverage }}
        </div>
        <div class="form-group">
             Cena: {{ order.final_price }}
        </div>
        <div class="form-group">
            <input type="submit" value="Potwierdź">
        </div>

    </form>
    </div>
    </div>

{% endblock %}

lunches/buy_lunch/templates/edit_menu.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    {% if not menu %}
         <div class="menu">Nie możesz edytować menu z przeszłości!</div>
    {% else%}
     <div class="menu">
    <h5>Edytuj lunch</h5>
    <form action="{%  url 'edit-menu' menu.id %}" method="post" class="form">
    {% csrf_token %}
    {{ form | crispy }}
    <input type="submit" value="Zapisz">
    </form>
     </div>



    {% endif %}

{% endblock %}

lunches/buy_lunch/templates/index.html
{% extends "base.html" %}
    {% load app_filters %}

{% block content %}
    <div class="menu">
    {% if not menu %}
          <div>Przepraszamy, dzisiaj nieczynne :(</div>
   {% else %}
    <h5>Lunch na dziś: {{ today |date:'d-m-Y' }}</h5>
        <div class="mb-2 mt-4">
        <h5><strong>Danie główne</strong></h5>
        <div>Mięsne: {{ menu.lunch_meat.lunch_name }}</div>
        <div>Wegetariańskie: {{ menu.lunch_vegetarian.lunch_name }}</div>
        <div>Wegańskie: {{ menu.lunch_vegan.lunch_name }}</div>
        </div>

        <div class="mb-2 mt-4">
     <h5><strong>Przystawki</strong></h5>
         <div>Sałatka: {{ menu.salad.appetizer_name }}</div>
         <div>Zupa: {{ menu.soup.appetizer_name }}</div>
        </div>
            {% if user.is_staff %}
            <div class="mb-2 mt-4">
             <a class="btn btn-primary btn-outline-dark" href="{% url 'today-orders' %}">Zamówienia na dziś</a>
            </div>
            {% elif user.is_authenticated %}
     <div class="mb-2 mt-4">
        <a class="btn btn-primary btn-outline-dark" href="{% url 'make-order' %}">Złóż zamówienie</a>
     </div>
         {% endif %}
    {% endif %}



{% endblock %}

lunches/buy_lunch/templates/logout.html
{% extends 'base.html' %}
{% block content %}
    <div class="text-center">
    <h4>Wylogowano</h4>
    <div>
        <a href="{% url 'login' %}">Zaloguj się ponownie</a>
    </div>
    </div>
{% endblock content %}

lunches/buy_lunch/templates/user_details.html
{% extends "base.html" %}
    {% load app_filters %}


{% block content %}
    <h5 class="text-center">Użytkownik {{ orders.user.username }}</h5>
    <table class="table table-striped">
    <thead>
    <tr><th scope="col">Data</th>
        <th scope="col">Lunch</th>
        <th scope="col">Rodzaj</th>
        <th scope="col">Cena</th>
        <th scope="col">Ocena</th>
        <th scope="col">Przystawka</th>
        <th scope="col">Rodzaj</th>
        <th scope="col">Cena</th>
        <th scope="col">Ocena</th>
        <th scope="col">Napój</th>
        <th scope="col">Cena</th>
        <th scope="col">Cena łącznie</th>
        <th scope="col">Otrzymane punkty</th>
        <th scope="col">Recenzja</th></tr>
    </thead>
    <tbody>
        {% for order in orders %}
       <tr ><td>{{ order.date | date:"d-m-Y" }}</td>
            <td>{{ order.lunch.lunch_name }}</td>
            <td>{{ order.lunch.lunch_type | lunch_type }}</td>
            <td>{{ order.lunch.lunch_price }}</td>
                {% if order.menureview_set.count == 0 %}
                     <td> </td>
                {% else %}
                    {% for lunch in order.menureview_set.all %}
                        <td>{{ lunch.lunch_stars }}</td>
                    {% endfor %}
                {% endif %}
            <td>{{ order.appetizer.appetizer_name }}</td>
            <td>{{ order.appetizer.appetizer_type | appetizer_type }}</td>
            <td>{{ order.appetizer.appetizer_price }}</td>

            {% if order.menureview_set.count == 0 %}
                     <td> </td>
                {% else %}
                    {% for appetizer in order.menureview_set.all %}
                        <td>{{ appetizer.appetizer_stars }}</td>
                    {% endfor %}
                {% endif %}

            <td>{{ order.beverage.beverage_name }}</td>
            <td>{{ order.beverage.beverage_price }}</td>
            <td>{{ order.final_price }}</td>
            <td>{{ order.points_collected }}</td>
           {% if order.menureview_set.count == 0 %}
           <td> </td>
                {% else %}
                    {% for review in order.menureview_set.all %}
                       <td><a href="{%  url 'review' review.id %}">{{ review.review |truncatechars:10 }}</a></td>
                    {% endfor %}
                {% endif %}
       </tr>


    {% endfor %}
    </tbody>
    </table>



{% endblock %}